HALF_WINDOW = 100
WINDOW = 2 * HALF_WINDOW  # 4k ok, 6k not ok
SLIGHTLY_LARGER_WINDOW = WINDOW + 50

#  for the 4k
# HALF_WINDOW = 2000
# WINDOW = 2 * HALF_WINDOW  # 4k ok, 6k not ok
# SLIGHTLY_LARGER_WINDOW = WINDOW + 1000
